apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    name: cpu-loader
  name: test-q15
spec:
  containers:
  - image: nginx
    name: test-q15
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
